USE Instacart;
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (1,'prepared soups salads');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (2,'specialty cheeses');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (3,'energy granola bars');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (4,'instant foods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (5,'marinades meat preparation');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (6,'other');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (7,'packaged meat');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (8,'bakery desserts');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (9,'pasta sauce');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (10,'kitchen supplies');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (11,'cold flu allergy');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (12,'fresh pasta');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (13,'prepared meals');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (14,'tofu meat alternatives');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (15,'packaged seafood');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (16,'fresh herbs');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (17,'baking ingredients');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (18,'bulk dried fruits vegetables');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (19,'oils vinegars');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (20,'oral hygiene');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (21,'packaged cheese');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (22,'hair care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (23,'popcorn jerky');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (24,'fresh fruits');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (25,'soap');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (26,'coffee');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (27,'beers coolers');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (28,'red wines');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (29,'honeys syrups nectars');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (30,'latino foods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (31,'refrigerated');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (32,'packaged produce');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (33,'kosher foods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (34,'frozen meat seafood');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (35,'poultry counter');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (36,'butter');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (37,'ice cream ice');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (38,'frozen meals');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (39,'seafood counter');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (40,'dog food care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (41,'cat food care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (42,'frozen vegan vegetarian');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (43,'buns rolls');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (44,'eye ear care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (45,'candy chocolate');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (46,'mint gum');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (47,'vitamins supplements');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (48,'breakfast bars pastries');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (49,'packaged poultry');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (50,'fruit vegetable snacks');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (51,'preserved dips spreads');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (52,'frozen breakfast');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (53,'cream');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (54,'paper goods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (55,'shave needs');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (56,'diapers wipes');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (57,'granola');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (58,'frozen breads doughs');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (59,'canned meals beans');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (60,'trash bags liners');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (61,'cookies cakes');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (62,'white wines');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (63,'grains rice dried goods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (64,'energy sports drinks');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (65,'protein meal replacements');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (66,'asian foods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (67,'fresh dips tapenades');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (68,'bulk grains rice dried goods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (69,'soup broth bouillon');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (70,'digestion');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (71,'refrigerated pudding desserts');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (72,'condiments');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (73,'facial care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (74,'dish detergents');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (75,'laundry');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (76,'indian foods');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (77,'soft drinks');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (78,'crackers');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (79,'frozen pizza');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (80,'deodorants');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (81,'canned jarred vegetables');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (82,'baby accessories');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (83,'fresh vegetables');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (84,'milk');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (85,'food storage');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (86,'eggs');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (87,'more household');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (88,'spreads');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (89,'salad dressing toppings');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (90,'cocoa drink mixes');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (91,'soy lactosefree');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (92,'baby food formula');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (93,'breakfast bakery');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (94,'tea');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (95,'canned meat seafood');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (96,'lunch meat');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (97,'baking supplies decor');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (98,'juice nectars');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (99,'canned fruit applesauce');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (100,'missing');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (101,'air fresheners candles');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (102,'baby bath body care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (103,'ice cream toppings');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (104,'spices seasonings');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (105,'doughs gelatins bake mixes');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (106,'hot dogs bacon sausage');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (107,'chips pretzels');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (108,'other creams cheeses');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (109,'skin care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (110,'pickled goods olives');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (111,'plates bowls cups flatware');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (112,'bread');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (113,'frozen juice');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (114,'cleaning products');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (115,'water seltzer sparkling water');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (116,'frozen produce');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (117,'nuts seeds dried fruit');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (118,'first aid');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (119,'frozen dessert');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (120,'yogurt');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (121,'cereal');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (122,'meat counter');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (123,'packaged vegetables fruits');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (124,'spirits');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (125,'trail mix snack mix');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (126,'feminine care');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (127,'body lotions soap');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (128,'tortillas flat bread');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (129,'frozen appetizers sides');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (130,'hot cereal pancake mixes');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (131,'dry pasta');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (132,'beauty');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (133,'muscles joints pain relief');
INSERT INTO AISLE (Aisle_ID, Aisle_Name) VALUES (134,'specialty wines champagnes');
