USE Instacart;
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (1,'frozen');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (2,'other');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (3,'bakery');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (4,'produce');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (5,'alcohol');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (6,'international');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (7,'beverages');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (8,'pets');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (9,'dry goods pasta');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (10,'bulk');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (11,'personal care');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (12,'meat seafood');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (13,'pantry');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (14,'breakfast');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (15,'canned goods');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (16,'dairy eggs');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (17,'household');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (18,'babies');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (19,'snacks');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (20,'deli');
INSERT INTO DEPARTMENT (Department_ID, Department_Name) VALUES (21,'missing');
