USE Cincinnati;
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2715000,"CFD - Response","CFD Rspnse",1);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904400,"ETS Information Security","ETSInfoSec",2);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2020000,"Parks -  Operations Land Manag","Parks - OP",3);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2220000,"CPD-Department of Police","CPD",4);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1030000,"Emergency Communication Center","ECC",5);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4302000,"WWB-Human Resource Mgmt","WWB HR",6);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977337,"CRC-Aquatics Gate Monitors","Aquatics",7);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4604000,"RCS-Laboratory","RCS Lab",8);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (290000,"Council - Kearney","CCLKearney",9);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1922410,"CRC-Pleasant Ridge Programs","PRidgeProg",10);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3014010,"CWW Business Services IT Devel","BusService",11);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977334,"CRC-Aquatics Lifeguards","Lifeguards",12);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1080000,"Performance & Data Analytics","PerfDataAn",13);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1914320,"CRC-Millvale/N.Fairmount","Mill/N.Fmt",14);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1913220,"CRC-Dunham/SP Janitorial","Dun/SP Jan",15);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1944612,"CRC-Maintenance Central - PT","Maint",16);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (110000,"Council - Greg Landsman","Landsman",17);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4303000,"WWB-Finance and Accounting","WWB Acctg",18);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1935220,"CRC-College Hill/Mt.Airy Jan","CH/MA Jan",19);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4206000,"WWE-Quality Assurance/Control","WWE Qual",20);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1913410,"CRC-Dunham SP Camps","DunhamCamp",21);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1929422,"CRC-Youth Summer Employ Corp","Youth Fam",22);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1370000,"Division Of Purchasing","Purchasing",23);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2532400,"Yard Waste Collections","PS YW Coll",24);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4460000,"WWT-Taylor Creek Section","WWT- TC",25);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977331,"CRC-Aquatics Administration","Aqua Adm",26);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1200000,"Human Resources Department","HR",27);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4203000,"WWE-Project Management","WWEProjMgm",28);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1942612,"CRC-Maintenance West - PT","Maint",29);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2117000,"B&I Permits Zoning Plan Review","B&I Zoning",30);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2030000,"Parks-Planning  Design & Dev","ParksPlan",31);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3071020,"CWW IT Program Management Serv","CWWITPMS",32);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1939310,"CRC-Non Fee Programs","CRC-Non Fe",33);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3062020,"CWW Inspection/Contract Admin.","CWWINSPECT",34);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1933220,"CRC-McKie/Camp Wash Janitor","McKCam Jan",35);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656570,"PHC Price Hill Medical Records","PH Recrds",36);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1916220,"CRC-Hartwell/Winton Hills Jani","Hartwell",37);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1354000,"Risk Mgmt-Workers' Compensatio","Work. Comp",38);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2621110,"HLT Administration","TRD Admin",39);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3052010,"CWW Richard Miller Plant","CWWMILLER",40);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4430000,"WWT-Little Miami Section","WWT-LM",41);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3110000,"CWW Stormwater Mgmt Utility","CWW SMU",42);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2511000,"Pub Svcs Director","PS Directr",43);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1111000,"Law - Civil Litigation","Civil Lit",44);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1910000,"CRC-Recreation - Region West","West",45);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1918220,"CRC-Lincoln Janitorial","LincolnJan",46);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2712000,"CFD - Support Services","CFD Supprt",47);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2120000,"B&I Property Maint Code Enforc","B&I PMCE",48);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4301000,"WWB-SBE Program","WWB SBE",49);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1342000,"Delinquent Accounts","Delinquent",50);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3011020,"Directors Section","DIR",51);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (907100,"ETS-CLEAR Information Systems","ETS CLEAR",52);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4310000,"WWB-Information Technology","WWB IT",53);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1943612,"CRC-Maintenance East - PT","Maint",54);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1919310,"CRC-Non Fee Programs","CRC-Non Fe",55);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1928220,"CRC-Oakley Janitorial","Oakley",56);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3026030,"CWW Administrative Support","AdmSupport",57);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977332,"CRC-Aquatics Pool Managers","Pool Mgrs",58);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1117000,"Law - Prosecution","Pros",59);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3053010,"CWW Distribution Unit","CWW Dist",60);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2121000,"B&I PMCE Code Enforcement","B&I Code E",61);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3063010,"CWW Plant Contract Admin.","CWWCONTADM",62);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3032010,"CWW Operations","CWWOPERATN",63);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1110000,"Law - Administration","Admin",64);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2525000,"Pub Svcs TRO Asphalt","PS TRO Asp",65);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1935320,"CRC-College Hill/ Mt. Airy","College H",66);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2660000,"School and Adolescent Health","SchAdHlth",67);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3072010,"CWW IT Cust Serv & Billing","CWWITCSS",68);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1924410,"CRC-Evanston Camps","Evanston",69);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1936220,"CRC-Corryville Janitorial","Corry Jan",70);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1928320,"CRC-Oakley Prgms","Oakley",71);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1915220,"CRC-WTH/Eng.Wds.Janitorial","WTH Jan",72);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033810,"CWW Maintenance Administration","CWWMAINADM",73);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3062030,"CWW System Records","CWWRECORDS",74);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1914220,"CRC-Millvale Janitorial","Mill Janit",75);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653510,"PHC Elm Street Dental Services","ES Dental",76);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1061000,"Retirement","CM RET",77);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1993930,"CRC-Financial Management","Fin Mgmt",78);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3044020,"CWW Maintenance","CWWMAINTNC",79);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1330100,"Financial Operations","Fin Oper",80);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655550,"PHC Northside Nurses","NS Nurses",81);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3024020,"CWW Billing System Processing","BillingSys",82);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1356000,"Risk Mgmt - PEAP","Risk-PEAP",83);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1615000,"DCD/Adm/Operations/Fiscal","DCD/Fiscal",84);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1970000,"CRC-Recreation - Athletics","Athletics",85);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1995280,"CRC-Arts and Grants","Arts & Gra",86);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4101000,"MSD-Office of the Director","MSD-OffDir",87);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1922420,"CRC-Pleas. Ridge Programs","PR Prgm",88);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1924220,"CRC-Evanston Janitorial","Evanston",89);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4508000,"WWC-Asset Renewal","WWC Asset",90);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2610000,"Hlt Div Of The Commissioner","Hlth Comm",91);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4601000,"RCS-Admin & Regulatory Complia","RCS Admin",92);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1928410,"CRC-Oakley Camps","Oakley",93);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4208000,"Facility Asset Management","FacAstMgmt",94);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1929220,"CRC-Janitorial","CRC-Janito",95);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4410000,"WWT- Office of Superintendent","WWT Supt",96);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2310000,"Transportation -Office of Dir","Director",97);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1927220,"CRC-Madisonville Janitor","Mad Jan",98);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1922220,"CRC-P.Ridge/K.W. Janitorial","PR Janitor",99);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4800000,"SBR-Sewer Backup Response","SBR Respon",100);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033890,"CWW Electrical Maintenance","CWWELECTRC",101);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2340000,"Transportation - Aviation","AVIA",102);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2613110,"Hlt Od/Ea Admin","OD/EAAdmin",103);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3022020,"CWW Customer Services","CWWCUSTSER",104);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4501000,"WWC-Administration and Support","WWC Admin",105);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (300000,"Office of the Mayor","Mayor",106);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1927410,"CRC-Madisonville Camps","Mad Camp",107);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2390000,"Traffic Engineering","Traffic En",108);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1112000,"Law - Administrative Hearings","Admin Hrg",109);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3052020,"CWW Charles M. Bolton Plant","WWG Bolton",110);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2553000,"CFM-Maintenane Services","Maint Serv",111);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1937220,"CRC-Hirsch/N. Avondale Janitor","Hirsch",112);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2221191,"CPD-School Crossing Guards","CPD-XingGD",113);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2532100,"Solid Waste Curbside Collectn","PS NO Coll",114);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1310000,"Finance-Office Of Director","Fin-Dir",115);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3062040,"CWW System Design","CWWDESIGN",116);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033870,"CWW Main Station Unit","CWWMAINSTA",117);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2526000,"Pub Svcs TRO Structures","PS TRO Str",118);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3015040,"CWW Accounting","CWW Accoun",119);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1640000,"Economic Development","CD Econ",120);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4490000,"WWT-Maintenance Section","Maint Sec",121);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1923220,"CRC-Bush Janitorial","Bush",122);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977338,"CRC-Aquatics Indoor Pools","Aquatics",123);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2022000,"Parks - Waterfront","Park-Water",124);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1941650,"CRC-Indoor Maintenance","Maint",125);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4502000,"WWC-Customer Service","WWC CustSv",126);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1937420,"CRC-Hirsch/N. Avondale  Prgms","Hirsch",127);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1923320,"CRC-Bush Programs","Bush",128);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1994940,"CRC-Personnel","Personnel",129);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1936410,"CRC-Corryville Camps","Corry Camp",130);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2714000,"CFD - Human Resources","CFD HR",131);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2320000,"Div of Trans  Planning & Urb D","T,P,UD",132);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2021000,"Park Board Greenleaf Summer Yo","Parks Summ",133);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4440000,"WWT-Muddy Creek Section","WWT- MC",134);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (100000,"City Council","Council",135);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1939220,"CRC-Seniors Janitorial","Senior Jan",136);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654515,"PHC Millvale Dental N-P","MV Den NP",137);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033850,"CWW Mechanical Maintenance","Mechanical",138);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4202000,"WWE-Construction","WWE Const",139);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1620000,"Neighborhood Develop/Adm","CD/Hse/Adm",140);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1934220,"CRC-Clifton Janitorial","Clifton Ja",141);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1919220,"CRC-Janitorial","CRC-Janito",142);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1914410,"CRC-Millvale/N.Fair Camps","Mill/N.Fmt",143);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1923410,"CRC-Bush Camps","Bush",144);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1914310,"CRC-Millvale/N.Fairmount","Mill/N.Fmt",145);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1912220,"CRC-PriceHill/Linc Janitorial","PH/Lin Jan",146);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1926220,"CRC-Mt. Wash Janitorial","Mt Wash Ja",147);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1360100,"Taxpayer Services & Education","Txpr Serv",148);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2713000,"CFD - Prevention & Comm Edu","CFD PreEdu",149);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1330600,"Financial Reporting for TIF","TIF",150);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1971960,"CRC-Athletic Administration","Athletic",151);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1017000,"Office of Human Relations","CM Hum Rel",152);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2113000,"B&I Permits Plan Examination","B&I Plan",153);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2330000,"Engineering","Engineerin",154);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (240000,"Council-Smitherman","Smitherman",155);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1371100,"Printing Services and Stores","Print Admi",156);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3062010,"CWW Survey","CWWSURVEY",157);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1992920,"CRC-Marketing","Marketing",158);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1010000,"Office of the City Manager","City Mgr",159);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2116000,"B&I Permits Elevator Inspectio","B&I Elevat",160);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2480100,"Parking Meter Install & Maint","PrkMtrInst",161);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3019010,"CWW Security Section","CWW Securi",162);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2523000,"Pub Svcs TRO Traffic Control","PS TRO Trf",163);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2811000,"Econ Incl-Contract Compliance","EI CCOMPL",164);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2633110,"CHS Lead Admin","Lead Adm",165);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2632310,"HLT CHS HP Cardiovas Health","Cardio Hth",166);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635350,"HLT CHS Envir. Food Serv. Oper","Food Serv",167);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1353000,"Risk Mgmt-Health Benefits","Health Ben",168);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1938410,"CRC-Bond Hill/Carthage Camps","Bond Hill",169);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2625220,"HLT Info. Systems Operations","Info Sy Op",170);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635345,"HTL CHS Envir Serv. Gen Envir","Gen Envir",171);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1800000,"Citizen's Complaint Authority","CM CCA",172);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611125,"Nursing Quality Assurance","Qual Asc",173);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2537000,"Greenspace & Lots","GS & Lots",174);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1926410,"CRC-Mt. Washington Camps","Mt Was Cam",175);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3016010,"CWW Human Resources","CWW HR",176);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (901100,"ETS-Office Of Director","ETS - Dir",177);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1916410,"CRC-Hart/Winton Hills Camp","Hartwell",178);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2560000,"Fleet Services","Fleet Serv",179);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3044030,"CWW Valve","CWWVALVE",180);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3044040,"CWW Support Services","CWWSUPPORT",181);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3062050,"CWW System Planning","CWWPLANING",182);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (903400,"ETS-E-Gov","ETS E-Gov",183);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1977333,"CRC-Aquatics Head Guards","Head Grds",184);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635375,"HLT CHS Environ Solid Waste","Sol Waste",185);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2115000,"B&I Permits Bldg Inspections","B&I Inspec",186);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2534400,"Neighborhood Right-Way CLNING","PS NGH CL",187);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (170000,"Council - Wendell Young","W Young",188);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2534100,"CBD Cleaning","PS CBD CLN",189);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3018010,"CWW Training Section","CWW Train",190);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1972710,"CRC-Softball","Softball",191);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4420000,"WWT-Millcreek Section","WWT-Mill",192);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3025040,"CWW  Premises Support","Prem Supp",193);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1351000,"Risk Management","Risk Mgmt",194);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1020000,"Budget & Evaluation","Budget",195);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1330400,"Payroll System","Payroll",196);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1932220,"CRC-Over The Rhine Janitorial","OTR Jan",197);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (909100,"ETS-Cin Area Geo Info Sys","ETS CAGIS",198);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1090000,"Internal Audit Division","Int Audit",199);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (400000,"Clerk of Council","CounclClrk",200);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635110,"CHS Environmental Administrati","Envir Adm",201);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3053030,"CWW WQT Administrative","CWW WQT Ad",202);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1711000,"City Planning/Land Use","CP/Land",203);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2631110,"HLT CHS Administration","CHS Admin",204);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2000000,"Department Of Parks","Parks",205);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3025020,"CWW Premises Services","PremisisSv",206);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4603000,"RCS-Industrial Waste","RCS IndusW",207);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656515,"PHC Price Hill Dental N-P","PH Den NP",208);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635380,"HLT CHS Envir Wte  Const & Dem","Const.",209);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1927320,"CRC-Madisonville","Madison",210);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4509000,"WWC-Mechanical Maintenance","WWC MechM",211);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2651110,"PHC Health Center Administrati","Hlth Ctr A",212);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2650000,"Health Create - HC","Health Cre",213);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2649110,"PHC Central Pharmacy\Stores","Cent Pharm",214);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1340000,"Division Of Treasury","Treasury",215);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1938320,"CRC-Bond Hill/Carthage","Bond Hill",216);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (903800,"ETS-Human Resource Info Sys","ETS CHRIS",217);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2659515,"HLT - Crest Smile Shoppe","CrestSmile",218);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2532200,"Tire Collection","PS TR Coll",219);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2641410,"HLT PHC IAP","PHC IAP",220);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2652000,"Hlt PHC-HC Cann Med Ctr","Hlt PHC-HC",221);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4300000,"WWB-Office of Business Service","WWB",222);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2640000,"Hlt Div Of Primary Hlt Care-Sp","Hlt Div Of",223);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1330200,"Infrastructure","Infrastruc",224);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645490,"PHC WIC Community Locations","WIC Com",225);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611115,"Clerk of Board of Health","Bd Clerk",226);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1921960,"CRC-Region 2 Administration","Reg 2 Adm",227);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2538000,"Street Sweeping","St Sweepin",228);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4602000,"RCS-Process Control","RCS Proces",229);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635370,"HLT CHS Environ General Wast","Gen Waste",230);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4703000,"WO-Wet Weather Facilities","WO WetWF",231);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655515,"PHC Northside Dental N-P","NS Den NP",232);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2481800,"Parking-Garfield Garage","Garfield",233);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2558000,"CFM-Architecture Design Serv","Architect",234);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2111000,"B&I Permits Administration","B&I Permit",235);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1118000,"Law - Real Estate","Real Est",236);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1916310,"CRC-Hartwell/Winton Hills","Hartwell",237);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (120000,"Council - Sittenfeld","Sittenfeld",238);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4505000,"WWC-Assessment and Cleaning","WWC Assess",239);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2657110,"PHC Clement Administration","AC Admin",240);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2114000,"B&I Permits Plumbing Inspectio","B&I Plumbi",241);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1944611,"CRC-Maintenance Central - FT","Maint",242);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4605000,"RCS-Safety","RCS Safety",243);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4201000,"WWE-Administration","WWE Admin",244);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1935410,"CRC-CollegeHill/Mt.Airy Camp","CH Camp",245);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1933410,"CRC-McKie/C.Wash Camps","McKie Camp",246);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1934410,"CRC-Clifton Camps","Clifton",247);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4400000,"Div of Wastewater Treatment","WWT",248);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2534600,"Private Lot Abatement","PS PR LOT",249);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1931960,"CRC-Region 3 Administration","Reg 3 Adm",250);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1996630,"CRC-Tech Service/Capital Imprv","Tech Serv",251);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904300,"ETS-800 MHZ System","ETS 800MHZ",252);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654550,"PHC Millvale Nurses","MV Nurses",253);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653550,"PHC Elm Street Nurses","ES Nurses",254);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1938220,"CRC-Bond Hill/Carthage Janitor","Bond Hill",255);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1929410,"CRC-Camps","CRC-Camps",256);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904100,"ETS-CTS Telephone System/Serv","ETS Phones",257);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654530,"PHC Millvale Physicians","MV Phys",258);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904600,"ETS Service Desk","ETSSerDesk",259);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033820,"CWW Preventative Maintenance","CWWPREVENT",260);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2489000,"Parking-Administration","Admin",261);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2652520,"PHC Caan Pharmacy","Cn Pharm",262);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1915310,"CRC-WTH/Eng.Wds.","WTH/Eng.W",263);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1350000,"Division Of Risk Management","Risk Mgmt",264);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1937310,"CRC-Hirsch/N. Avondale","Hirsch",265);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1924310,"CRC-Evanston","Evanston",266);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3011030,"Lead Section","LEAD",267);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2527000,"Pub Svcs TRO Traf Sig Sys","PS TRO TSS",268);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1918410,"CRC-Lincoln Camps","Linc Camps",269);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3025030,"CWW Auxiliary Services","Auxiliary",270);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645491,"PHC WIC City Health Centers","WIC City",271);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1974430,"CRC-Seniors","CRC-Senior",272);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653515,"PHC Elm Street Dental N-P","ES Den NP",273);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1915410,"CRC-Westwood TH camps","WestwCamps",274);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3053020,"CWW Analytical Unit","WWG Anal",275);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3013010,"CWW Stores","CWWSTORES",276);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4204000,"WWE-Dev Svcs & Conveyance Plan","WWE DSCP",277);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1610000,"DCD/Administration","DCD/Adm",278);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2513000,"Pub Svcs - HR & Systems","PS HR & Sy",279);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3025060,"Delinquent Service Order Sect","Meter Read",280);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1937410,"CRC-Hirsch/N.Avondale Camps","Hirsch",281);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2642423,"HLT PHC CNS Speciaty Programs","Spec Prog",282);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1934320,"CRC-Clifton","Clifton",283);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2530000,"PS-Neighborhood Operations Div","NOD",284);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1943611,"CRC-Maintenance East - FT","Maint",285);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2635355,"HLT CHS Envir. Envirome Tech","Envir Tech",286);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1360300,"Delinquency Resolution","DRS",287);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3063020,"CWW Plant Plan & Spec. Studies","CWWPLANSTD",288);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1939320,"CRC-Programs","CRC-Progra",289);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2657520,"PHC Clement Pharmacy","AC Pharm",290);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1972751,"CRC-National Junior Tennis","CRC-Nation",291);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1330300,"Financial Reporting","Fin Report",292);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1932310,"CRC-Over The Rhine","Otr",293);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1937320,"CRC-Hirsch/N. Avondale","Hirsch",294);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655000,"Hlt PHC-HC Northside Med Ctr","Hlt PHC-HC",295);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4704000,"WO-Remote Monitoring","WO RemoteM",296);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3015010,"Procurement Section","PROCUR",297);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1929310,"CRC-Non Fee Programs","CRC-Non Fe",298);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653520,"PHC Elm Street Pharmacy","ES Pharm",299);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2641110,"PHC Administraion","PHC Adm.",300);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4506000,"WWC-Asset Management","WWC Asset",301);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3017010,"CWW Business Services Mgmt","CWW Bus Se",302);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2657550,"PHC Clement Nurses","AC Nurses",303);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1936310,"CRC-Corryville","Corryville",304);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1938310,"CRC-Bond Hill/Carthage","Bond Hill",305);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656530,"PHC Price Hill Physicians","PH Phys",306);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4450000,"WWT-Sycamore Section","WWT- Syc",307);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1201000,"Human Resources Director's Off","HR Directr",308);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2632315,"HLT CHS HP Education","HP Educ",309);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3024030,"CWW Payments & Collections","Pay&Collct",310);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1932320,"CRC-Over The Rhine","Otr",311);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654520,"PHC Millvale Pharmacy","MV Pharm",312);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611140,"HLT-Bio Terrorism Grant","Bio Terror",313);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1918310,"CRC-Lincoln","Lincoln",314);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (903200,"ETS-Financial System","ETS - CFS",315);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4305000,"WWB-Training","WWB Train",316);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1918320,"CRC-Lincoln Programs","LincolnPrg",317);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1933310,"CRC-McKie / Camp Wash","McKie Camp",318);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1912410,"CRC-Price Hill/Lincoln Camps","PriceHCamp",319);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656550,"PHC Price Hill Nurses","PH Nurses",320);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655510,"PHC Northside Dental Services","NS Dental",321);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1976750,"CRC-Tennis","Tennis",322);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (900000,"Enterprise Tech Solutions","ETS",323);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1927310,"CRC-Madisonville","Madisonv",324);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2646110,"PHC Dental Administration","Dental Adm",325);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1919410,"CRC-Camps","CRC-Camps",326);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611120,"Medical Director's Office","Med Dir",327);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4470000,"WWT Polk Run Section","Polk Run",328);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1923310,"CRC-Bush","Bush",329);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (902400,"ETS-Application Services","ETS App Sv",330);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1641000,"Business Dev/Small Business","CD/BD/SB",331);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1935420,"CRC-College Hill/Mt. Airy Prgm","CH Prg",332);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611110,"Health Dept. Administration","Hth Admin",333);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3012010,"CWW Fleet Maintenance","CWWFLTMANT",334);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1912310,"CRC-Price Hill/Lincoln","P.H./Pine",335);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1341000,"Cash Management/Banking","Cash Mgmt",336);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1932410,"CRC-Over The Rhine Camps","OTR Camps",337);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1939410,"CRC-Camps","CRC-Camps",338);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1114000,"Law - Economic & Community Dev","Econ & CD",339);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3011040,"Media/Marketing Section","MEDMAR",340);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1936320,"CRC-Corryville","Corryville",341);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2810000,"Economic Inclusion Department","Econ Inclu",342);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4700000,"WO-Watershed Operations Admin","WO Admin",343);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2010000,"Parks-Directors Office","ParksDirec",344);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2636110,"Hlt CHS Ces Cd Admin","Hlt CHS Ce",345);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2112000,"B&I Permits Customer Service","B&I Custom",346);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3025050,"Meter Reading & New Accounts S","Meter Read",347);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1360400,"Document Management","Doc Mgmt",348);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645000,"Hlt PHC-Sp Women/Infan & Child","Hlt PHC-Sp",349);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1040000,"Ofc Environmental Sustainabili","OES",350);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2711000,"CFD - Executive Office","CFD Exec",351);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4503000,"WWC-Equipment and Vehicles","WWC Equip",352);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (905100,"ETS-HAMCO","ETS HAMCO",353);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1913320,"CRC-Dunham/Sayler Park","Dunham/SP",354);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655520,"PHC Northside Pharmacy","NS Pharm",355);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655110,"PHC Northside Administration","NS Admin",356);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904500,"ETS-Data Infrastructure","ETS DtaInf",357);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2625230,"HLT Info Systems Development","Info Sys D",358);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1352000,"Risk Mgmt-Employee Health Serv","Emp Hlth",359);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2622110,"HLT Financial Management","Fin Mgt",360);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656520,"PHC Price Hill Pharmacy","PH Pharm",361);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2528000,"Pub Svcs TRO Rdwy Light Sys","PS TRO RLS",362);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2642440,"HLT PHC CNS West Distr Admin","WD Adm",363);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1343000,"Licensing - Administration Tax","Licensing",364);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2652110,"PHC Caan Administration","Cn Admin",365);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2647000,"Hlt PHC-Sp Clement Med Ctr","Hlt PHC-Sp",366);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1912320,"CRC-Price Hill/Lincoln","P.H./Lin",367);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645110,"PHC WIC Administration","WIC Adm",368);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1360200,"Compliance","Compliance",369);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1927420,"CRC-Madisonville Programs","Mad Prog",370);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1710000,"City Planning/Administration","CP/Adm",371);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655512,"PHC Northside Dental Hygiene","NS Den Hy",372);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645492,"PHC WIC Contract Clinics","WIC Cont",373);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2512000,"Pub Svcs - Fin & Quality Cntrl","PS Fin QC",374);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2556000,"CFM-City Hall Operations","City Hall",375);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2647110,"Hlt PHC-Sp Ac Admin","Hlt PHC-Sp",376);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4705000,"WO-Hydraulic Modeling","WO Hydraul",377);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (903000,"ETS-CINSY Information System","ETS Cinsy",378);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653110,"PHC Elm Street Administration","ES Admin",379);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1012000,"Office of Communications","Comm",380);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4701000,"WO-Stormwater Control Measures","WO StormCo",381);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4306000,"WWB-CIP Program Controls","WWB CIP",382);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654110,"PHC Millvale Administration","MV Admin",383);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2652550,"PHC Caan Nurses","Cn Nurses",384);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653000,"Hlt PHC-HC Elm Street Med Ctr","Hlt PHC-HC",385);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1951960,"CRC-Golf Administration","Golf Adm",386);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1991910,"CRC-Director & Mktg/PR","Director",387);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1942611,"CRC-Maintenance West - FT","Maint",388);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1924320,"CRC-Evanston Prgms","Evanston",389);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654510,"PHC Millvale Dental Services","MV Dental",390);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (4507000,"WWC-Facilities","WWC Facili",391);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (909200,"ETS-CSR System Support","ETS CSR SS",392);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1926320,"CRC-Mt. Washington Programs","Mt Was Pro",393);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2645493,"PHC WIC Hospital Locations","WIC Hosp",394);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (150000,"Council - David Mann","D. Mann",395);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1922320,"CRC-Pleasant Rdge/Ken-Wdfrd","Pr/Kw",396);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1913420,"CRC-Dunham/Sayler Pk Programs","Dun/SP Prg",397);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1915420,"CRC-Westwood Programs","WTH Prgm",398);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656110,"PHC Price Hill Administration","PH Admin",399);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1916320,"CRC-Hartwell/Winton Hills","Hartwell",400);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2611130,"Communicable Disease","Com Dis",401);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (3033860,"CWW Charles M. Bolton Unit","CWWBLTUNT",402);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (280000,"Council - Sundermann","CCL Sunder",403);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1915320,"CRC-WTH/Eng.Wds.","WTH/Eng.W",404);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1933320,"CRC-McKie /Camp Wash","McKie Camp",405);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1919320,"CRC-Programs","CRC-Progra",406);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1913310,"CRC-Dunham/Sayler Park","Dunham/SP",407);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2200000,"Police Department","Police",408);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (160000,"Council - Seelbach","Seelbach",409);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2552000,"CFM-Property Mgmt","Prop Mgmt",410);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (260000,"Council - Jeff Pastor","Pastor",411);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2534700,"City Wide Dumpster Program","PS DUMP P",412);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2626110,"TRD Maintenance","Maint",413);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2536000,"Pub Svcs NO Customer Service","PS NO CS",414);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2534300,"Graffiti Abatement","PS GRAF AB",415);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1929320,"CRC-Programs","CRC-Progra",416);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2654320,"Hlt PHC-HC Mv X-Ray","Hlt PHC-HC",417);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2642435,"HLT PHC CNS MCH Home Nursing","MCH Home",418);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2657620,"PHC STD Control Program","Std Contrl",419);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (904200,"ETS-Fiber Communications","ETS Fiber",420);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653570,"PHC Elm Street Medical Records","ES Rcords",421);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2642445,"HLT PHC CNS WD Home Nursing","WD Home",422);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2646511,"PHC Dental Occlusal\Sealant","Occ\Seal",423);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653512,"PHC Elm Street Dental Hygiene","ES Den Hy",424);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2630000,"HLT Community Healthcare","Community",425);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2642455,"HLT PHC CNS NCS Home Nursing","NCS Home",426);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (1911960,"CRC-Region 1 Administration","Reg 1 Adm",427);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2655530,"PHC Northside Physicians","NS Phys",428);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2653530,"PHC Elm Street Physicians","ES Phys",429);
INSERT INTO DEPARTAMENT (Departament_Code,Departament_Name,Departament_ABBRV,Departament_id) VALUES (2656510,"PHC Price Hill Dental Services","PH Dental",430);
