USE Cincinnati;
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("352","Fire Fighter-96 hr","Fire Fight",1);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("046","Information Technology Mgr-EXM","InfoTechMg",2);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("151","Supvr Prks/Rec Mnt & Const-EXM","Spv P/R Mn",3);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("110","Division Manager","Div MGR",4);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("052","Clerk Typist 2","Clerk Typ2",5);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("313","Co-Op/Student Intern 3","Co-Op/Int3",6);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("953","Parks/Recreation Program Ldr","P/R Prg Ld",7);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("909","Recreation Specialist","Rec Specls",8);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("054","Chemist-EXM","Chemist",9);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("023","Council Assistant","CounclAsst",10);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("139","Computer Systems Analyst-EXM","Computer S",11);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("911","Lifeguard","Lifeguard",12);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("094","Management Analyst-EXM","Management",13);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("578","Service Area Coordinator-EXM","SvcAreaCor",14);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("369","Fire Apparatus Operator-96 hr","FAO",15);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("359","Fire Captain-96 hr","Fire Capt",16);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("932","Municipal Worker","Munc Wkr",17);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("377","Police Officer","Police Off",18);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("111","Senior Accountant-EXM","Senior Acc",19);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("515","Supervising Engineer-EXM","Supv Eng",20);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("008","Administrative Technician-EXM","Administra",21);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("321","Finance Manager-EXM","Finance Mg",22);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("360","Fire District Chief-96 hr","FirDistrCh",23);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("119","Plant Supervisor-EXM","Plant Supe",24);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("089","Human Resources Analyst-EXM","Human Reso",25);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("395","Emergency 911 Operator","911 Oper",26);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("043","Senior Cmptr/Prgrmr Anlyst-EXM","Senior Com",27);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("597","Park Naturalist","Park Natur",28);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("465","Asst Supvr of Constructn Insp","AstSpvrCtn",29);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("266","Medical Assistant","Med Asst",30);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("013","Senior Admin Spec-EXM","Senior Adm",31);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("304","Treatment Supervisor-EXM","Treatment",32);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("712","Plant Maintenance Specialist","PlntMaintS",33);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("888","Public Services Director","PubSrvDir",34);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("167","Senior Asst City Solicitor-EXM","SrAsCtySol",35);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("405","Emergency Srvcs Dsptch Supvr","Emergency",36);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("434","Inspector  1","Inspector1",37);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("177","Senior Management Analyst-EXM","Senior Man",38);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("535","Deputy Director","Dep Dir",39);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("407","Operator And Dispatcher","Oper Disp",40);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("908","Pool Manager","Pool Manag",41);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("166","Asst City Solicitor-EXM","AstCtySol",42);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("358","Fire Lieutenant-96 hr","Fire Lieut",43);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("284","Senior Chemist-EXM","Senior Che",44);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("430","Inspector Trainee","InspectTrn",45);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("357","Paramedic Training Officer","ParTrngOff",46);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("539","Water Works Chief Engineer-EXM","WW ChEng",47);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("273","Senior Engineer-EXM","Sen Enginr",48);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("709","Plant Operator 2","PlantOper2",49);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("242","Health Programs Manager-EXM","Health Pro",50);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("651","Truck Driver","Truck Driv",51);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("986","Optometrist","Optometris",52);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("168","Asst Treatment Supt-EXM","Ast Trt Sp",53);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("021","Civil Service Commissioner","CvlServCmm",54);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("523","Civil Engineering Technician 3","CET 3",55);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("159","Supvg Hmn Resrcs Anl-EXM","Supv HR An",56);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("252","Dentist-EXM","Dentist",57);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("385","Police Lieutenant","Police Lt",58);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("149","Senior Human Res Analyst-EXM","Sr HR Anl",59);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("001","Administrative Specialist-EXM","Administra",60);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("364-8","Assistant Fire Chief-80 hr","AsstFireCh",61);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("258","Accountant - EXM","Accountant",62);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("759","Water Works Maint Field Supvr","WWMntFldS",63);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("277","Public Health Nurse 2","PH Nurse 2",64);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("247","Public Health Consultant","HlthConsu",65);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("826","Emergency Comm Asst Mgr","EmCommAM",66);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("755","Water Works Maintenance Worker","WWMaintWrk",67);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("041","Supervising Management Analyst","SupvMgmAn",68);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("658","Motor Equipment Operator 2","MEO 2",69);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("805","Sewer Maintenance Crew Leader","Sewer Main",70);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("307","Supervising Epidemiologist","Supv Epide",71);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("256","Treatment Superintendent-EXM","Treatment",72);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("217","Legal Assistant-EXM","Legal Asst",73);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("274","Nurse Practitioner-EXM","Nurse Prac",74);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("165","Senior Engineering Technician","Senior Eng",75);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("520","Electrical Maintnce Supvr-EXM","Electrical",76);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("931","Administrative Hearing Officer","AdminOfcr",77);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("601","Laborer","Laborer",78);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("619","Heat Ventilation & Air Conditi","Heat Venti",79);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("045","Information Tech Asst Mgr-EXM","InfoTechAM",80);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("920","School Crossing Guard","Xing Guard",81);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("062","Clerk Typist 3","Clerk Typ3",82);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("656","Sanitation Specialist","SanitSpec",83);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("602","Sanitation Helper","SanittHlpr",84);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("144","Pub Wrks Oprtns Supvr-EXM","PW Opr Spv",85);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("053","Buyer-EXM","Buyer",86);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("044","Technical Systems Analyst-EXM","TechSysAna",87);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("108","Assistant Finance Director","Ast Fin Dr",88);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("254","Supvg Accountant-EXM","Supv Acct",89);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("621","Painter","Painter",90);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("384","Police Sergeant","Police Sgt",91);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("634","Carpenter","Carpenter",92);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("632","Cement Finisher","Cement Fin",93);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("613","Electrical Maint Worker 1","Emw 1",94);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("156","Senior Development Officer-EXM","Senior Dev",95);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("510","Engineer Intern-EXM","Engineer I",96);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("630","Bricklayer","Bricklayer",97);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("849","Florist","Florist",98);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("198","Wastewater Collction Supvr-EXM","Wastewater",99);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("841","Tree Maintenance Worker","Tree Maint",100);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("626","Plumber","Plumber",101);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("617","Electrician","Electrici",102);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("027","Council Member","CouncilMem",103);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("614","Electrical Maint Worker 2","Emw 2",104);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("026","Mayor","Mayor",105);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("251","Dental Assistant","DentalAsst",106);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("576","Development Manager-EXM","Devlp Mgr",107);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("640","Supervisor of Maintenance","SupvMaint",108);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("855","Facility Maintenance Specialis","FacMntSpec",109);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("622","Painter Crew Leader","PaintCrLdr",110);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("701","Plant Maintenance Worker","PlntMaintW",111);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("358-8","Fire Lieutenant-80 hr","Fire Lt",112);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("360-8","Fire District Chief-80 hr","Dist Chief",113);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("867","Bldg & Grnds Mnt Crw Ldr-EXM","BldGrnMCL",114);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("382","Police Specialist","PoliceSpec",115);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("191","Asst To The City Solicitor-EXM","AtoSolictr",116);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("047","Senior Bldng Plans Examner-EXM","Bldg Pln E",117);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("216","Principal Engineer-EXM","Principal",118);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("122","Permit Technician 1","PermiTech1",119);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("880","Printing Srvc & Stores Mgr-EXM","Printing S",120);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("235","Senior Real PropertySpecialist","SrRlPropSp",121);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("141","Supervising Buyer-EXM","Supv Buyer",122);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("521","Civil Engineering Technician 1","CET1",123);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("754","Water Works Maintenance Crew L","WWMaintCrw",124);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("690","Parking Enforcement Officer &","PEO&Meter",125);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("725","Sewer Construction Inspector","MSDConInsp",126);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("972","Contract Compliance Spec-EXM","CompSpec",127);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("457","Senior Sanitarian","SrSanitari",128);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("756","Customer Relations Representat","CustRelRep",129);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("429","Inspector 2","Inspector2",130);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("101","Parks/Rec Maintenance Crew Ldr","P/R MtncCL",131);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("657","Motor Equipment Operator 1","MEO1",132);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("016","Asst To The City Manager-EXM","Ast to CM",133);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("723","Wastewater Collection Eq Spec","WWCollEqSp",134);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("875","Supervising Storekeeper","SupStorekp",135);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("074","CCA Director","CCA Dir",136);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("463","Water Works Construction Inspe","WWConstIns",137);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("689","Parking Enforcement Officer","PrkgEnfOff",138);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("667","Automotive Mechanic","Auto Mech",139);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("752","Water Works Valve Operator 1","ValveOper1",140);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("084","Engineering Technical Spvr","Eng Tch Sp",141);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("289","Laboratory Technician 2","Lab Tech 2",142);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("386","Police Captain","PoliceCapt",143);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("456","Sanitarian","Sanitarian",144);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("472","Public Works Inspector 2","PW Insp 2",145);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("582","Community Center Director","ComCtrDir",146);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("707","Plant Operator 1","PlantOper1",147);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("762","Supvr of Water Dist Mnt-EXM","SupWtrDist",148);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("201","Occupational Sfty/Hlth Crd-EXM","Occ Saf Cr",149);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("131","Supvg Envrnmntl/Sfty Spc-EXM","SupvEnvSaf",150);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("373","Crime Analyst","CrimeAnl",151);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("751","Water Works Valve Operator 2","ValveOper2",152);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("999","Internal Audit Manager-EXM","Int Aud Mg",153);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("035","Deputy Clerk","Dep Clerk",154);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("259","Environmental Services Dir-EXM","Environmen",155);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("721","Wastewater Collection Crew Lea","WWCollLdr",156);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("486","Supervising City Planner-EXM","SupvPlannr",157);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("388","Assistant Police Chief","AsstPolChf",158);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("203","Public Health Educator-EXM","Public Hea",159);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("767","Water Customer Service Rep 1","CustSrvRe1",160);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("606","Pretreatment Specialist","PretreatSp",161);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("522","Civil Engineering Technician 2","CET 2",162);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("278","Public Health Nurse 3","PH Nurse 3",163);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("674","Maint Fabrication Specialist","MntFabSpec",164);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("095","Nursing Supervisor-EXM","Nursing Su",165);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("604","Utility Technician","Util Tech",166);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("233","Pharmacy Director-EXM","Pharmacy D",167);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("757","Water Works Dispatcher","WWDispatc",168);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("314","Co-Op/Student Intern 4","Co-Op/Stud",169);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("311","Co-Op/Student Intern 1","Co-Op/Int1",170);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("091","Industrial Investigator-EXM","Industrial",171);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("352-8","Fire Fighter-80 hr","Firefighte",172);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("120","Retirement Director","Retire Dir",173);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("257","Pub Wks/Utilities Supt-EXM","PW/Ut Spt",174);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("874","Storekeeper","Storekeepe",175);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("265","City Planner-EXM","Cty Planr",176);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("170","City Solicitor-EXM","City Solic",177);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("551","Supvg Parks/Recreation Crd-EXM","SupRecCoor",178);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("106","Accounting Technician 3","AcctTech3",179);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("641","Maintenance Crew Leader","MaintCrwLd",180);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("529","Supvg Bldg Plns Exm Cd Anl-EXM","SupBldPln",181);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("919","Parking Attendant","PrkgAttdt",182);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("020","City Manager-EXM","City Mgr",183);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("891","Assistant City Manager","Ast Cty Mg",184);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("542","Facilities Manager-EXM","Facilities",185);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("998","Spvg Real Estate Specialist","SpRESp",186);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("435","Supervising Inspector","SupInspect",187);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("264","Asst Spvr of Inspections","As Spv Ins",188);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("267","Casework Associate","Casework A",189);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("200","Dietitian-EXM","Dietitian",190);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("157","Chief Counsel-EXM","Chief Coun",191);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("253","Pub Wrks Oprtns Supt-EXM","Public Wor",192);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("611","Electrical Maintenance Worker3","EMW3",193);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("497","Engineering Technician 3","Eng Tech 3",194);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("675","Maint. Fabrication Crew Leader","MntFabCrLd",195);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("404","Radio Operator-Technician 2","RadioOper2",196);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("255","Supvg Architect-EXM","Supv Arch",197);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("262","Public Health Pediatrician-EXM","PH Pedtrcn",198);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("408","Asst Operator And Dispatcher","Asst Oper",199);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("703","Plant Operator 2 - Ohio Class","PlantOper2",200);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("295","Pharmacy Technician","Pharm Tech",201);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("130","Senior Envrnmntl/Sfty Spec-EXM","Senior Env",202);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("441","Zoning Plan Examiner-EXM","Zoning Pla",203);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("474","Wastewater Collection Inspecto","WW ColIns",204);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("768","Water Customer Service Rep 2","CustSrvRe2",205);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("695","Welder Helper","Welder Hlp",206);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("291","Laboratory Technician 4","Lab Tech 4",207);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("459","Sanitarian-In-Training","SanitarTrn",208);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("685","Asst Fleet Srvcs Mgr-EXM","AstFleetMg",209);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("375","Police Criminalist","Police Cri",210);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("620","Sign Painter","Sign Paint",211);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("042","Computer Programmr/Analyst-EXM","Computer P",212);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("983","Employmnt & Training Supvr-EXM","Employment",213);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("461","Litter Control Officer","LitterCont",214);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("028","Senior Police Technician","Sr Pol Tec",215);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("458","Supvg Sanitarian-EXM","SupvSantrn",216);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("250","Dental Hygienist","Dental Hyg",217);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("061","Clerk 3","Clerk 3",218);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("223","Chief Appraiser","Chief Apsr",219);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("541","Asst Facilities Mntnc Mgr-EXM","AsstFMMgr",220);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("107","Pharmacist-EXM","Pharmacist",221);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("686","Fleet Services Manager-EXM","Fleet Serv",222);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("487","Urban Conservator-EXM","Urban Cons",223);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("603","Utility Laborer","UtilityLab",224);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("359-8","Fire Captain-80 hr","FireCapt80",225);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("051","Clerk 2","Clerk 2",226);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("494","Electronics Technician 2","ElecTech 2",227);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("208","City Architect-EXM","City Archi",228);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("286","Supervising Chemist-EXM","Supv Chem",229);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("100","Accounting Technician 1","AcctTech 1",230);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("282","Nursing Director-EXM","Nursing Di",231);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("924","Water Works Guard","WW Guard",232);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("607","Building Maintenance Worker","BldgMaint",233);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("249","Public Health Practitioner-EXM","Public Hea",234);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("713","Plant Operator 2-OH Cert 3","PlantOp2C3",235);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("518","Principal Architect-EXM","Principal",236);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("720","Service Crew Leader","ServCrwLdr",237);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("692","Parking Superintendent-EXM","Parking Su",238);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("066","Development Officer-EXM","Dev Offcr",239);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("758","Senior Customer Relations Rep","SrCusRelRp",240);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("367-8","Fire Specialist-80 hr","Fire Spec",241);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("987","Optician","Optician",242);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("029","Law Enforcement Instructor","LawEfInstr",243);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("188","Real Estate Manager-EXM","RE Mgr",244);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("312","Co-Op/Student Intern 2","Co-Op/int2",245);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("178","Medical Director-EXM","Medical Di",246);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("227","Dental Director-EXM","Dental Dir",247);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("150","Senior Internal Auditor-EXM","Sr Int Aud",248);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("679","Maintenance Machinist","MaintMach",249);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("696","Welder","Welder",250);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("708","Structures Maintenance Worker","StructMain",251);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("088","Health Counselor-EXM","Health Cou",252);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("009","Investigator-EXM","Investigat",253);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("239","Expanded Function Dental Asst","EFDentAsst",254);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("072","Environmental/Safety Spec-EXM","Environmen",255);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("098","Fleet Services Supervisor","Fleet Spvr",256);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("197","Vital Statistics Coord-EXM","Vital Stat",257);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("926","City Planning Technician 2","PlanTech 2",258);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("039","Asst Supvr of Customer Service","AstSpvrCSv",259);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("927","City Planning Technician 3","PlanTech 3",260);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("672","Asst Supvr of Fleet Services","AstSupFlSv",261);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("504","Surveyor","Surveyor",262);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("234","Real Property Specialist","RealPropSp",263);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("104","Plant Maintenance Supvr-EXM","Plnt Mnt S",264);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("193","Support Services Specialst-EXM","SupSpvsSpe",265);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("152","Senior City Planner-EXM","Senior Cit",266);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("143","Senior Buyer-EXM","Senior Buy",267);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("080","Graphic Designer-EXM","Graphic De",268);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("824","Information Technology Coor","InfoTechCr",269);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("503","Supvg Surveyor-EXM","SupvSurvyr",270);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("169","Deputy City Solicitor-EXM","DepCitSolc",271);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("970","Transportation & Eng Dir","TrnsEngDir",272);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("389","Police Chief","Police Chf",273);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("221","Health Counseling Supvr-EXM","Health Cou",274);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("511","Architect Intern-EXM","Architect",275);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("225","Senior Real Est Spec-EXM","Sr Rl Es S",276);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("490","City Planning Director-EXM","Cty Pln Dr",277);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("365","Fire Chief        80 hr","Fire Chief",278);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("033","Environmental Programs Mgr-EXM","Env Prg Mg",279);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("004","ETS Director-EXM","ETS Dir",280);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("498","Engineering Technician 4","Eng Tech 4",281);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("115","Finance Director-EXM","Finance Dr",282);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("869","Supervisor of Urban Forestry","SupUrbFors",283);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("988","Optometric Technician","Optometric",284);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("704","Senior Plant Operator","Sr Plnt Op",285);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("187","Law Chief of Staff","LawChfStff",286);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("735","Director of Water-EXM","Dir of Wtr",287);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("609","Supvr Of Industrial Waste-EXM","SupIndWast",288);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("660","Automotive Street Cleaning Equ","AutoStCln",289);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("196","Video Production Spec-EXM","Video Prod",290);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("525","Deputy Public Works Dir-EXM","Dep PW Dr",291);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("411","Public Vehicle Investigator","PubVehInv",292);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("871","Urban Forestry Specialist","UrbanFstyS",293);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("305","Epidemiologist","Epidemiolo",294);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("682","Parking Services Supvr-EXM","Parking Se",295);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("534","Deputy Director Econ Inclusion","Dep Dir EI",296);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("559","Assistant Recreation Director","Ast Rec Dr",297);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("984","Director Community & Econ Dev","DirCED",298);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("677","Automotive Mechanic-Crew Chief","AutoCrwChf",299);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("050","Senior Architect-EXM","Sen Archtc",300);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("691","Asst Supvr of Prkng Svcs-EXM","AsstSupPrk",301);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("350","Paramedic Coordinator-EXM","Paramedic",302);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("056","Computer Operator 2","CompOper2",303);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("211","Supvg Dietitian-EXM","SupvDietcn",304);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("086","Secretary","Secretary",305);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("508","Engineering Geologist-EXM","Engineerin",306);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("199","Wic Program Coordinator-EXM","Wic Progra",307);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("105","Accounting Technician 2","AcctTech 2",308);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("821","Communications Supervisor","Comm Supvr",309);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("288","Laboratory Technician 1","Lab Tech 1",310);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("659","Motor Equipment Operator 3","MEO 3",311);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("180","Senior Plant Supervisor-EXM","Senior Pla",312);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("114","Director of Economic Inclusion","Econ Inc D",313);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("989","Deputy Director Water & Sewer","DepDirWS",314);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("155","Human Resources Director-EXM","HR Dir",315);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("347","Graphic Design Supvr-EXM","Graphic De",316);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("372","Senior Crime Analyst","SrCrimeAnl",317);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("059","Dir of Perform & Data Analytic","DirP&DA",318);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("195","Utilities Const Inspect-EXM","Utilities",319);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("205","Health Commissioner-EXM0","Hlth Comm",320);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("446","Building & Inspections Dir-EXM","Bldg In Dr",321);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("825","Senior Info Technology Coor","SrInfoTchC",322);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("895","Airport Maintenance Worker","AirMntWrkr",323);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("784","Wastewater Collection Pipelaye","WWCollPip",324);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("530","Sewers Director-EXM","Sewers Dir",325);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("985","Deputy Dir Community & Econ De","DepDirCED",326);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("204","Assistant Health Commissioner","Ast Hlth C",327);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("280","Breast Feeding Peer Counselor","BFP Coun",328);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("842","Tree Maintenance Crew Leader","TreeMainCr",329);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("560","Recreation Director-EXM","Recrtn Dir",330);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("865","Parks Director-EXM","Parks Dir",331);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("828","Emergency Comm Center Dir","ECC Dir",332);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("770","Cement Gun Utility Worker","Cem GunWrk",333);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("290","Laboratory Technician 3","Lab Tech 3",334);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("376","Police Recruit","Police Rec",335);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("791","Traffic Aids Worker","TrafficAid",336);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("065","Supervising Clerk","Supvg Clrk",337);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("902","Cleaner","Cleaner",338);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("567","Turf Manager","Turf Manag",339);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("236","Supervising Real Property Spec","SupRlPrSpc",340);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("049","Clerk Typist 1","Clerk Typ1",341);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("673","Maint Fabrication Apprentice","MntFabAppr",342);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("214","Home Health Aide","HomeHltAid",343);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("799","Equipment Dispatcher 2","EquipDis2",344);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("413","Telecommunication Specialist 2","TeleSpec2",345);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("460","Industrial Waste Inspector","IndWaste",346);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("879","Reproduction Machine Oper 3","RepreMach3",347);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("665","Tire Repair Worker","TireRepair",348);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("287","Laboratory Assistant","Lab Asst",349);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("790","Supvg Traffic Aids Worker","SupTrafAid",350);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("396","Asst Fire Alarm Operator And D","Asst Alarm",351);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("030","Police Technician","PoliceTech",352);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("683","City Stormwater Mgmt Engnr-EXM","City Storm",353);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("219","Peap Coordinator-EXM","Peap Coord",354);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("263","Public Health Physician-EXM","PH Physcn",355);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("190","Zoning Hearing Examiner","ZongHrgExm",356);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("154","Senior Comm Dev Analyst-EXM","Sr CD Anal",357);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("024","Chief Deputy Clerk Of Council","Ch DepClk",358);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("058","CommunityDvlpmnt&Plan Anal-EXM","ComD&P An",359);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("092","Internal Auditor-EXM","Internal A",360);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("261","Public Health Internist-EXM","PH Intern",361);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("323","Training Coordinator","TrainCoord",362);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("135","Commercial Services Supt-EXM","Commercial",363);
INSERT INTO JOB (Job_Code,Job_Name,Job_ABBRV,Job_id) VALUES ("025","Clerk Of Council","Clk Councl",364);
