USE Louisvilleky;
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Belle of Louisville",1);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Civic Innovation & Technology",2);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Codes & Regulations",3);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Commonwealth Attorney",4);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Community Services",5);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Coroner",6);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Corrections",7);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("County Attorney",8);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Develop Louisville",9);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Economic Development",10);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Emergency Mgt Agency/MetroSafe",11);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Fire & Rescue",12);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Fleet & Facilities",13);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Human Relations Commission",14);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Human Resources",15);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Internal Auditor",16);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Kentuckiana Works Foundation",17);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Library",18);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Louisville Metro Council",19);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Louisville Metro EMS",20);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Mayor's Office",21);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Metro Animal Services",22);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Metro Criminal Justice Comm",23);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Metro Parks & Recreation",24);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Metro Police",25);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Office of Performance Improvmt",26);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("OMB",27);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Other Officials",28);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Parking Authority of River Cty",29);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Public Health & Wellness",30);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("PW&A",31);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Safe & Healthy Neighborhoods",32);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Waterfront Development Corp",33);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Youth Detention Services",34);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("Zoo",35);
INSERT INTO DEPARTAMENT (Departament_Name,Departament_id) VALUES ("All Metro Gov",36);
