USE Louisvilleky;
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","UNKNOWN","UNKNOWN","UNKNOWN","UNKNOWN",1);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","MALE","5 to 9.9 years",2);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","1 to 4.9 years",3);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","Over 20",4);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","MALE","Under 1 year",5);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","Under 1 year",6);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","MALE","1 to 4.9 years",7);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","HISPA","MALE","1 to 4.9 years",8);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","UNKNOWN","UNKNOWN","UNKNOWN","UNKNOWN",9);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","Under 1 year",10);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","MALE","Under 1 year",11);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","MALE","1 to 4.9 years",12);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","1 to 4.9 years",13);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","Over 20",14);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","5 to 9.9 years",15);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","5 to 9.9 years",16);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","10 to 14.9 years",17);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","5 to 9.9 years",18);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","BLACK","MALE","Under 1 year",19);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","FEMALE","Under 1 year",20);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","MALE","1 to 4.9 years",21);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","FEMALE","Under 1 year",22);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","Over 20",23);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","MALE","5 to 9.9 years",24);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","MALE","Under 1 year",25);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","Over 20",26);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","BLACK","MALE","Under 1 year",27);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","Over 20",28);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","MALE","5 to 9.9 years",29);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","FEMALE","Under 1 year",30);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","1 to 4.9 years",31);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","MALE","Under 1 year",32);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","Under 1 year",33);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","FEMALE","1 to 4.9 years",34);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","MALE","1 to 4.9 years",35);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","FEMALE","5 to 9.9 years",36);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","1 to 4.9 years",37);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","Under 1 year",38);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","Over 20",39);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","ASIAN","FEMALE","5 to 9.9 years",40);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","FEMALE","1 to 4.9 years",41);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","1 to 4.9 years",42);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","FEMALE","1 to 4.9 years",43);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","Over 20",44);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","Over 20",45);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","FEMALE","Under 1 year",46);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","WHITE","MALE","Under 1 year",47);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","15 to 19.9 years",48);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","10 to 14.9 years",49);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","10 to 14.9 years",50);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","FEMALE","5 to 9.9 years",51);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","Under 1 year",52);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","FEMALE","1 to 4.9 years",53);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","HISPA","MALE","Under 1 year",54);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","MALE","Over 20",55);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","15 to 19.9 years",56);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","MALE","Under 1 year",57);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","1 to 4.9 years",58);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","5 to 9.9 years",59);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","Over 20",60);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","WHITE","UNKNOWN","Under 1 year",61);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","5 to 9.9 years",62);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","FEMALE","1 to 4.9 years",63);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","ASIAN","FEMALE","10 to 14.9 years",64);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","15 to 19.9 years",65);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","FEMALE","1 to 4.9 years",66);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","MALE","Under 1 year",67);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","MALE","1 to 4.9 years",68);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","5 to 9.9 years",69);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","BLACK","FEMALE","1 to 4.9 years",70);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","MALE","1 to 4.9 years",71);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","BLACK","FEMALE","Under 1 year",72);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","1 to 4.9 years",73);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","10 to 14.9 years",74);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","Over 20",75);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","5 to 9.9 years",76);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","FEMALE","5 to 9.9 years",77);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","5 to 9.9 years",78);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","10 to 14.9 years",79);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","10 to 14.9 years",80);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","MALE","Under 1 year",81);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","MALE","Under 1 year",82);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","WHITE","FEMALE","Under 1 year",83);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","FEMALE","Under 1 year",84);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","MALE","5 to 9.9 years",85);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","1 to 4.9 years",86);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","BLACK","MALE","1 to 4.9 years",87);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","FEMALE","5 to 9.9 years",88);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","FEMALE","Over 20",89);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","BLACK","MALE","1 to 4.9 years",90);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","MALE","1 to 4.9 years",91);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","WHITE","FEMALE","1 to 4.9 years",92);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","FEMALE","5 to 9.9 years",93);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","10 to 14.9 years",94);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","BLACK","MALE","Under 1 year",95);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","1 to 4.9 years",96);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","WHITE","MALE","1 to 4.9 years",97);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","Under 1 year",98);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","Under 1 year",99);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","5 to 9.9 years",100);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","MALE","5 to 9.9 years",101);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","15 to 19.9 years",102);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","5 to 9.9 years",103);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","Under 1 year",104);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","10 to 14.9 years",105);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","15 to 19.9 years",106);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","MALE","1 to 4.9 years",107);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","1 to 4.9 years",108);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","MALE","10 to 14.9 years",109);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","FEMALE","1 to 4.9 years",110);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","BLACK","FEMALE","Under 1 year",111);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","15 to 19.9 years",112);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","MALE","5 to 9.9 years",113);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","MALE","Over 20",114);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","BLACK","FEMALE","1 to 4.9 years",115);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","BLACK","MALE","1 to 4.9 years",116);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","FEMALE","Under 1 year",117);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","5 to 9.9 years",118);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","15 to 19.9 years",119);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","BLACK","FEMALE","1 to 4.9 years",120);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","BLACK","FEMALE","Under 1 year",121);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","FEMALE","15 to 19.9 years",122);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","5 to 9.9 years",123);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","Under 1 year",124);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","Under 1 year",125);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","15 to 19.9 years",126);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","MALE","15 to 19.9 years",127);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","MALE","Under 1 year",128);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","10 to 14.9 years",129);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","1 to 4.9 years",130);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","10 to 14.9 years",131);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","10 to 14.9 years",132);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","MALE","1 to 4.9 years",133);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","FEMALE","1 to 4.9 years",134);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","WHITE","MALE","5 to 9.9 years",135);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","BLACK","MALE","Under 1 year",136);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","WHITE","FEMALE","1 to 4.9 years",137);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","MALE","15 to 19.9 years",138);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","FEMALE","Under 1 year",139);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","BLACK","FEMALE","Under 1 year",140);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","Under 1 year",141);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","HISPA","FEMALE","1 to 4.9 years",142);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","MALE","1 to 4.9 years",143);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","FEMALE","10 to 14.9 years",144);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","HISPA","FEMALE","1 to 4.9 years",145);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","HISPA","FEMALE","1 to 4.9 years",146);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","1 to 4.9 years",147);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","FEMALE","10 to 14.9 years",148);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","FEMALE","5 to 9.9 years",149);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","1 to 4.9 years",150);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","MALE","Over 20",151);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","10 to 14.9 years",152);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","5 to 9.9 years",153);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","MALE","15 to 19.9 years",154);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","BLACK","FEMALE","Under 1 year",155);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","1 to 4.9 years",156);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","1 to 4.9 years",157);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","UNKNOWN","FEMALE","Under 1 year",158);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","MALE","Over 20",159);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","MALE","Over 20",160);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","FEMALE","Under 1 year",161);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","HISPA","FEMALE","1 to 4.9 years",162);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","MALE","15 to 19.9 years",163);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","Over 20",164);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","5 to 9.9 years",165);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","FEMALE","5 to 9.9 years",166);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","HISPA","FEMALE","Under 1 year",167);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","5 to 9.9 years",168);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","HISPA","MALE","Over 20",169);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","1 to 4.9 years",170);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","FEMALE","Under 1 year",171);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","15 to 19.9 years",172);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","HISPA","MALE","Under 1 year",173);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","Over 20",174);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","15 to 19.9 years",175);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","MALE","5 to 9.9 years",176);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","UNKNOWN","MALE","Under 1 year",177);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","UNKNOWN","FEMALE","Under 1 year",178);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","AMIND","FEMALE","5 to 9.9 years",179);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","UNKNOWN","FEMALE","Under 1 year",180);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","WHITE","FEMALE","1 to 4.9 years",181);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","Under 1 year",182);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","UNKNOWN","FEMALE","Under 1 year",183);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","UNKNOWN","MALE","1 to 4.9 years",184);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","UNKNOWN","FEMALE","Under 1 year",185);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","UNKNOWN","MALE","1 to 4.9 years",186);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","UNKNOWN","MALE","Under 1 year",187);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","UNKNOWN","FEMALE","Under 1 year",188);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","UNKNOWN","MALE","Under 1 year",189);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","UNKNOWN","MALE","Under 1 year",190);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","UNKNOWN","FEMALE","1 to 4.9 years",191);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","ASIAN","FEMALE","1 to 4.9 years",192);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","UNKNOWN","FEMALE","Under 1 year",193);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","UNKNOWN","FEMALE","1 to 4.9 years",194);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","UNKNOWN","FEMALE","Under 1 year",195);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","UNKNOWN","MALE","Under 1 year",196);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","UNKNOWN","FEMALE","Under 1 year",197);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","MALE","10 to 14.9 years",198);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","MALE","15 to 19.9 years",199);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","UNKNOWN","MALE","1 to 4.9 years",200);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","UNKNOWN","MALE","Under 1 year",201);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","UNKNOWN","FEMALE","Under 1 year",202);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","10 to 14.9 years",203);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","BLACK","FEMALE","1 to 4.9 years",204);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","10 to 14.9 years",205);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","UNKNOWN","FEMALE","Under 1 year",206);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","FEMALE","1 to 4.9 years",207);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","UNKNOWN","MALE","Under 1 year",208);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","UNKNOWN","MALE","1 to 4.9 years",209);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","UNKNOWN","MALE","Under 1 year",210);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","Under 1 year",211);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","MALE","10 to 14.9 years",212);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","15 to 19.9 years",213);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","UNKNOWN","MALE","Under 1 year",214);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","MALE","1 to 4.9 years",215);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","FEMALE","5 to 9.9 years",216);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","BLACK","MALE","1 to 4.9 years",217);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","FEMALE","Over 20",218);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","WHITE","FEMALE","15 to 19.9 years",219);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","BLACK","MALE","5 to 9.9 years",220);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","HISPA","MALE","15 to 19.9 years",221);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","BLACK","FEMALE","1 to 4.9 years",222);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","FEMALE","1 to 4.9 years",223);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","MALE","1 to 4.9 years",224);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","UNKNOWN","FEMALE","5 to 9.9 years",225);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","UNKNOWN","MALE","Under 1 year",226);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","UNKNOWN","MALE","Under 1 year",227);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","UNKNOWN","FEMALE","1 to 4.9 years",228);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","UNKNOWN","FEMALE","1 to 4.9 years",229);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","UNKNOWN","FEMALE","Under 1 year",230);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","UNKNOWN","FEMALE","1 to 4.9 years",231);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","UNKNOWN","FEMALE","1 to 4.9 years",232);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","UNKNOWN","MALE","1 to 4.9 years",233);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","UNKNOWN","FEMALE","Under 1 year",234);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","UNKNOWN","FEMALE","1 to 4.9 years",235);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","ASIAN","MALE","5 to 9.9 years",236);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","FEMALE","5 to 9.9 years",237);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","UNKNOWN","FEMALE","1 to 4.9 years",238);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","UNKNOWN","MALE","1 to 4.9 years",239);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","ASIAN","MALE","Over 20",240);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","UNKNOWN","MALE","1 to 4.9 years",241);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","UNKNOWN","MALE","1 to 4.9 years",242);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","FEMALE","Over 20",243);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","UNKNOWN","MALE","1 to 4.9 years",244);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","UNKNOWN","FEMALE","Under 1 year",245);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","UNKNOWN","MALE","1 to 4.9 years",246);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","UNKNOWN","MALE","1 to 4.9 years",247);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","UNKNOWN","FEMALE","Under 1 year",248);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","UNKNOWN","MALE","Under 1 year",249);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","MALE","10 to 14.9 years",250);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","HISPA","FEMALE","1 to 4.9 years",251);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","15 to 19.9 years",252);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","MALE","10 to 14.9 years",253);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","5 to 9.9 years",254);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","BLACK","MALE","1 to 4.9 years",255);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","10 to 14.9 years",256);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","Over 20",257);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","UNKNOWN","MALE","Under 1 year",258);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","UNKNOWN","FEMALE","1 to 4.9 years",259);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","ASIAN","MALE","10 to 14.9 years",260);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","FEMALE","10 to 14.9 years",261);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","UNKNOWN","MALE","1 to 4.9 years",262);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","UNKNOWN","MALE","1 to 4.9 years",263);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","MALE","Over 20",264);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","FEMALE","Over 20",265);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","UNKNOWN","MALE","Under 1 year",266);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","BLACK","FEMALE","5 to 9.9 years",267);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","Under 1 year",268);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","MALE","Over 20",269);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","FEMALE","10 to 14.9 years",270);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","5 to 9.9 years",271);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","10 to 14.9 years",272);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","10 to 14.9 years",273);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","WHITE","MALE","5 to 9.9 years",274);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","ASIAN","MALE","Under 1 year",275);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","BLACK","MALE","5 to 9.9 years",276);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","BLACK","FEMALE","Under 1 year",277);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","FEMALE","15 to 19.9 years",278);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","FEMALE","15 to 19.9 years",279);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","WHITE","FEMALE","5 to 9.9 years",280);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","MALE","10 to 14.9 years",281);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","FEMALE","1 to 4.9 years",282);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","WHITE","FEMALE","Under 1 year",283);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","Under 1 year",284);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","FEMALE","Under 1 year",285);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","FEMALE","10 to 14.9 years",286);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","1 to 4.9 years",287);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","ASIAN","FEMALE","1 to 4.9 years",288);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","MALE","Under 1 year",289);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","Over 20",290);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","AMIND","FEMALE","1 to 4.9 years",291);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","ASIAN","MALE","1 to 4.9 years",292);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","HISPA","MALE","Under 1 year",293);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","WHITE","MALE","5 to 9.9 years",294);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","FEMALE","5 to 9.9 years",295);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","ASIAN","FEMALE","5 to 9.9 years",296);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","WHITE","MALE","Under 1 year",297);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","MALE","5 to 9.9 years",298);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","MALE","Under 1 year",299);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","BLACK","MALE","1 to 4.9 years",300);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","MALE","Under 1 year",301);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","MALE","Over 20",302);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","HISPA","MALE","5 to 9.9 years",303);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","ASIAN","MALE","1 to 4.9 years",304);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","BLACK","FEMALE","5 to 9.9 years",305);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","MALE","Under 1 year",306);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","MALE","1 to 4.9 years",307);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","FEMALE","Over 20",308);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","Under 1 year",309);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","BLACK","MALE","5 to 9.9 years",310);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","ASIAN","FEMALE","Under 1 year",311);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","MALE","Under 1 year",312);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","FEMALE","Over 20",313);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","BLACK","FEMALE","10 to 14.9 years",314);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","Over 20",315);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","UNKNOWN","FEMALE","1 to 4.9 years",316);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","ASIAN","FEMALE","1 to 4.9 years",317);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","PACIF","FEMALE","1 to 4.9 years",318);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","10 to 14.9 years",319);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","15 to 19.9 years",320);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","UNKNOWN","FEMALE","1 to 4.9 years",321);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","WHITE","MALE","1 to 4.9 years",322);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","HISPA","MALE","5 to 9.9 years",323);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","WHITE","MALE","Over 20",324);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","WHITE","MALE","15 to 19.9 years",325);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","AMIND","FEMALE","Under 1 year",326);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","FEMALE","Under 1 year",327);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","HISPA","MALE","Over 20",328);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","HISPA","MALE","Under 1 year",329);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","WHITE","MALE","Under 1 year",330);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","MALE","10 to 14.9 years",331);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","ASIAN","MALE","1 to 4.9 years",332);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","UNKNOWN","FEMALE","5 to 9.9 years",333);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","10 to 14.9 years",334);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","BLACK","FEMALE","Over 20",335);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","5 to 9.9 years",336);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","UNKNOWN","MALE","Under 1 year",337);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","WHITE","MALE","1 to 4.9 years",338);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","ASIAN","FEMALE","Under 1 year",339);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","FEMALE","5 to 9.9 years",340);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","AMIND","MALE","10 to 14.9 years",341);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","UNKNOWN","FEMALE","1 to 4.9 years",342);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","UNKNOWN","FEMALE","Under 1 year",343);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","1 to 4.9 years",344);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","MALE","10 to 14.9 years",345);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","FEMALE","1 to 4.9 years",346);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Under 20","ASIAN","FEMALE","Under 1 year",347);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","MALE","5 to 9.9 years",348);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Under 20","UNKNOWN","MALE","1 to 4.9 years",349);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","ASIAN","MALE","Under 1 year",350);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","BLACK","MALE","10 to 14.9 years",351);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","BLACK","FEMALE","1 to 4.9 years",352);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","45 to 59 years","UNKNOWN","FEMALE","1 to 4.9 years",353);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","HISPA","FEMALE","1 to 4.9 years",354);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","WHITE","FEMALE","10 to 14.9 years",355);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","BLACK","MALE","1 to 4.9 years",356);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","BLACK","FEMALE","Over 20",357);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","ASIAN","MALE","5 to 9.9 years",358);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","HISPA","FEMALE","5 to 9.9 years",359);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","ASIAN","MALE","Under 1 year",360);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","FEMALE","1 to 4.9 years",361);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","ASIAN","MALE","5 to 9.9 years",362);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","WHITE","MALE","1 to 4.9 years",363);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","MALE","Under 1 year",364);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","HISPA","MALE","5 to 9.9 years",365);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","MALE","Over 20",366);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","BLACK","FEMALE","15 to 19.9 years",367);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","UNKNOWN","FEMALE","Under 1 year",368);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","FEMALE","Under 1 year",369);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","HISPA","MALE","1 to 4.9 years",370);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Under 20","UNKNOWN","FEMALE","1 to 4.9 years",371);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","UNKNOWN","MALE","1 to 4.9 years",372);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","FEMALE","5 to 9.9 years",373);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","HISPA","FEMALE","5 to 9.9 years",374);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","20 to 29 years","HISPA","FEMALE","Under 1 year",375);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","BLACK","MALE","10 to 14.9 years",376);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","HISPA","FEMALE","Over 20",377);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","60 to 74 years","WHITE","FEMALE","10 to 14.9 years",378);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","WHITE","FEMALE","15 to 19.9 years",379);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","MALE","15 to 19.9 years",380);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","HISPA","FEMALE","10 to 14.9 years",381);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","FEMALE","10 to 14.9 years",382);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","60 to 74 years","BLACK","MALE","1 to 4.9 years",383);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","ASIAN","MALE","Over 20",384);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","45 to 59 years","ASIAN","MALE","15 to 19.9 years",385);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","20 to 29 years","HISPA","FEMALE","1 to 4.9 years",386);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","UNKNOWN","MALE","Under 1 year",387);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","HISPA","MALE","10 to 14.9 years",388);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","HISPA","FEMALE","10 to 14.9 years",389);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","Over 74","BLACK","FEMALE","Over 20",390);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","Over 74","UNKNOWN","FEMALE","1 to 4.9 years",391);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","5 to 9.9 years",392);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","Over 74","WHITE","FEMALE","Over 20",393);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("TEMPORAL","30 to 44 years","UNKNOWN","FEMALE","1 to 4.9 years",394);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","20 to 29 years","HISPA","MALE","1 to 4.9 years",395);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","30 to 44 years","ASIAN","FEMALE","5 to 9.9 years",396);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","HISPA","FEMALE","5 to 9.9 years",397);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","AMIND","MALE","Over 20",398);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("REGULAR","60 to 74 years","ASIAN","MALE","Over 20",399);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","30 to 44 years","WHITE","FEMALE","Over 20",400);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","HISPA","MALE","15 to 19.9 years",401);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","BLACK","FEMALE","15 to 19.9 years",402);
INSERT INTO EMPLOYEE_PROFILE (Type_Employee,Age_Range,Ethnic_Group,Gender,Years_Worked_Range,Employee_Profile_id) VALUES ("UNKNOWN","45 to 59 years","AMIND","MALE","Over 20",403);
