USE Louisvilleky;
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Animal Bite",1);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Bite",2);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Burn from heat",3);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Chest Pain",4);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Contusion/Bruise",5);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Cut or Laceration",6);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Cut, laceration or scratches",7);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Sprain  (ligament)",8);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Sprain or Strain",9);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Sudden Illness",10);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Fracture",11);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Wound from a weapon",12);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Foreign Body",13);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Foreign Body (splinter)",14);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Human Bite",15);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Infection",16);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Other",17);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Bloodborne Disease",18);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Bloodborne Pathogen Exposure",19);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Concussion-Brain, cerebral",20);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Contact dermatitis (Rash, Poison Ivy)",21);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Inflammation",22);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Inhilation of an unknown substance",23);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Respiratory Disorders",24);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Respiratory Irritation",25);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Puncture",26);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("NULL",27);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Dislocation",28);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Burn",29);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Burn from chemical",30);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Heat Illness",31);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Multiple injuries",32);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Multiple natures",33);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Inflamation",34);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Irritation",35);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Strain (muscle/tendon)",36);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Tear of muscle/tendon/ligament",37);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Crushing",38);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Cumulative Injury",39);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Eye Injury",40);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Hernia",41);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Hyperextension",42);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Dehydration",43);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Insect Bite",44);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Poisoning - Chemical",45);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Scratches, abrasions-superficial",46);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Electric Shock, electrocution",47);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Insect Sting",48);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Poisoning - animal / insect",49);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Carpal Tunnel",50);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Exhaustion",51);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Tendonitis",52);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Chemical Exposure",53);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Cold Illness",54);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Privacy",55);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Exposure to Substance",56);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Amputation or enucleation",57);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Stress",58);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Hernia, rupture",59);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Bacteria",60);
INSERT INTO OSHA_TYPE (OSHA_Description,OSHA_Type_id) VALUES ("Asthma",61);
