USE Louisvilleky;
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("UNKNOWN","UNKNOWN",1);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("End Temporary Employment","Temp/Seasonal",2);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Normal Retirement","Retired",3);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Dismissed during Probation","Involuntary",4);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Resignation","Voluntary",5);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Administration Change","Involuntary",6);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Job Abandonmnt - DO NOT REHIRE","Voluntary",7);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("End Seasonal Employment","Temp/Seasonal",8);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Dismissed - DO NOT REHIRE","Involuntary",9);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Term Due to Lay Off","Involuntary",10);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Elimination of Position","Involuntary",11);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("No Show - DO NOT REHIRE","Other",12);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Resignation - DO NOT REHIRE","Voluntary",13);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Resigned during Probation","Voluntary",14);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Early Retirement","Retired",15);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Death","Other",16);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Dismissed - Elig for Rehire","Involuntary",17);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Resigned in Lieu of Dismissal","Voluntary",18);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Release (BXers)","Involuntary",19);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Health Reasons","Other",20);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Disability","Retired",21);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Dismissed Probtn - NO REHIRE","Involuntary",22);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Normal Retire - DO NOT REHIRE","Retired",23);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Failure to Return from Leave","Voluntary",24);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Unable To Accommodate","Involuntary",25);
INSERT INTO TURNOVER_REASON (Description_Reason,Description_Leave_Type,Turnover_Reason_id) VALUES ("Unsatisfactory Performance","Involuntary",26);
