USE Louisvilleky;
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","OVA","Overtime 1.5",1);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","OVT","Overtime 1.0",2);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","COT","Court Overtime Pay 1.5",3);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","WHO","Work at Higher Class Overtime",4);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","OVB","Overtime 2.0",5);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","SOV","Scheduled Overtime",6);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("OTHER OVERTIME","WHD","Work at Higher Class Double",7);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","PPT","Permanent Part Time",8);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","REG","Regular Base Pay",9);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","SEA","Seasonal",10);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","TEM","Regular Temporary",11);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","RE4","Permanent Hourly",12);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","TRN","Training",13);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","WH4","Work at Higher Class - Wkly",14);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","FGP","Foster Grandparents",15);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("REGULAR TIME","WHC","Work At a Higher Class - Biwky",16);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("SCHEDULED OVERTIME","SOV","Scheduled Overtime",17);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("SCHEDULED OVERTIME","WHS","Work Higher Class- Sch. OT",18);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("UNSCHEDULED GENERAL FUND OVERTIME","OVA","Overtime 1.5",19);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("UNSCHEDULED GENERAL FUND OVERTIME","OVT","Overtime 1.0",20);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("UNSCHEDULED GENERAL FUND OVERTIME","OVB","Overtime 2.0",21);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("UNSCHEDULED GENERAL FUND OVERTIME","WHO","Work at Higher Class Overtime",22);
INSERT INTO WORKED_HOURS_TYPE (Description_Type_Worked_Hours,Code_Hours_Type,Name_Hours_type,Worked_Hours_Type_id) VALUES ("UNSCHEDULED GENERAL FUND OVERTIME","WHD","Work at Higher Class Double",23);
